export { default as SignUp } from './SignUp'
export { default as Login } from './Login'
export { default as Navbar } from './Navbar'
export { default as PhotoAlbum } from './PhotoAlbum'
export { default as TabsComponent } from './TabsComponent'