export { default as SignUp } from './SignUp';
export { default as Login } from './Login';
export { default as Navbar } from './Navbar';
export { default as HumanForm } from './HumanForm';
export { default as DogComponent } from './DogComponent';
export { default as TabsComponent } from './TabsComponent';
export { default as Avatar } from './Avatar';
export { default as MapInput } from './MapInput';
export { default as RoutineComponent } from './RoutineComponent';
export { default as MultiplePhotoUpload } from './MultiplePhotoUpload'
